### ISSUE TITLE
Multi inverter support

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#126]
From the community:

> Supporting multiple inverters from different manufacturers at the same time is quite relevant. Most manufacturers only show info about their own products, so there is an open market for aggregating info from multiple brands and displaying overall data for the end customer.

I guess this would entail some aggregation of data at some point. e.g. one inverter producing 5kw and another 10kw at approximately the same time should be aggregated into 15kw. How should this be handled? In the gw? in the backend?

**Comment by h0bb3** [comment]
This has been brought up again by the community. We need to think about how to handle this from a DER and rewards point of view also.

**Comment by VIKOLO** [comment]
But to start with we could require one GW per inverter? If things get to complicated from a technical perspective.

**Comment by erikarenhill** [comment]
if I may add some thoughts here, from my experience (as also already stated at discord, but adding here for future reference :)):

- Many consumers are getting a separate inverter just for adding a battery dedicated for grid tied services (think checkwatt or flower hub)
- Some are having multiple batteries, one for own use and one for grid services
- Some are getting multiple inverters for expanding their solar production to multiple buildings (think private person living in a small farm, or in the countryside, adding panels on both roof and ground with separate inverters).

Requiring consumers to buy multiple gateways is a quite large investment for many (until they can actually see the ROI in terms of real money/time), and if/when adding multiple support later on it would render the extra gateways unnecessary, selling them in the used market is of course an option.

As a single user may have multiple inverters of different brands that are responding on modbus tcp maybe not at the same time personally I think you would just forward the raw data to backend where you have the possibility to aggregate them as you want or even change it during beta without collecting new data. That decision is or course up to you but I'm thinking that if the GW is aggregating the data, you loose both flexibility and the ability to verify that a specific inverter is not measuring correctly.

Also if the project aims to be environmental friendly, getting more hardware is a bad thing if it's possible to use a single gw

**Comment by davmoz** [comment]
*reviving*
![image](https://github.com/user-attachments/assets/4d2dad03-f38a-4c19-8d03-fdddbfcb3315)

**Comment by davmoz** [comment]
Thanks for the input, @erikarenhill! 
This should now be possible as of 7f8c9b5f727ceefb65775fa11adc31860620c1a4 and will be rolled out on the next release  (Nov 6th, 2024).  

Short:
A modbus configuration is saved for every unique (by MAC/SN) successful connection. The configurations are saved in the `state` (saved in RAM) and `settings` (saved in Backend).

If the gateway reboots -> It fetches the settings from backend and tries to open every single saved configuration and the `state` updates accordingly. 

The user should be able to reset the `settings`, but that's for another issue. closing.
