### ISSUE TITLE
transition to open-source 

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#130]
Let's discuss what parts to simplify (if any) before making this repo public. 

Some issues to address: 
- The README contains a lot of balena-related info, perhaps less focus on that
- Some of the compose files contain balena-specific flags and variables and need to contain specific paths when built on non-balena operating systems
- See if some parts of the code need improvement in terms of naming, refactoring, and comments
- Decide if the code should be split into smaller modules
- What parts to test and how to test them, e.g. flashing the firmware and onboarding the egw using the configurator(?)
- Decide open-source license

**Comment by h0bb3** [comment]
I guess most of this stuff has been taken care of or already decided. closing...
