### ISSUE TITLE
dual mining compose update

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#131]
The dual mining compose needs an update to incorporate the correct environment variables. see the Normal docker file.

It also seems to have balena labels left in it - these should probably be removed.

**Comment by davmoz** [comment]
https://github.com/NebraLtd/hm-diag/blob/6d5674070e3a1c0a82e32b013c5017610c685eb4/hw_diag/utilities/balena_supervisor.py#L23

**Comment by h0bb3** [comment]
The gpi button seems to collide with something giving

RuntimeError: Failed to add edge detection

This crashes the whole configurator making that part unusable.

**Comment by h0bb3** [comment]
Maybe this could be a starting point for the gpio issue... it seems to be some spi configuration that needs to happen

https://github.com/chirpstack/chirpstack-gateway-os/issues/71

**Comment by h0bb3** [comment]
an overlay was needed for the spi configuration 

`dtoverlay=spi0-1cs`

Now the configuration service also runs and enables ble for the rak gw when pressing the button.

![image](https://github.com/srcfl/srcful-gateway/assets/3469312/8e19048f-85c0-4b38-9fcb-3070a9fd9394)

I consider this finished.
