### ISSUE TITLE
Gateway serial number and public key not showing sometimes...

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#132]
This has happened when using Balena os and Raspbian. 

<img width="1144" alt="image" src="https://github.com/srcfl/srcful-gateway/assets/26165830/13dff73d-7177-4523-9486-0f09e4ce6ab2">

**Comment by h0bb3** [comment]
Another instance of this on a RAK v2 running in fleet Beta #151

![image](https://github.com/srcfl/srcful-gateway/assets/3469312/8f14e2c5-b707-4331-9f31-b613869e4872)

**Comment by h0bb3** [comment]
This could potentially/probably be fixd by now. So I will close this as we will see in the next firmware release if the problem was removed.
