### ISSUE TITLE
Post Balena Name to Backend

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#145]
We currently have no connection of the chip-serial, pubkey in the backend. This could become a problem as more devices are added into our fleet - i.e. dead reflashed devices that should be purged.

I propose posting this information into our backend. Possibly it could be handled via bash - or a small service of its own. A bit sceptical to add it to the server as we have kept it free of balena stuff so far.

**Comment by davmoz** [comment]
This should not be responsibility of the gateway, we let dashboard handle this
