### ISSUE TITLE
Variable harvest registers

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#148]
It would be more optimal to just read everything once per harvest-transport and then just a minimal set of registers. This would send less data over the network and also increase performance of the inverter connection.

This should not be hard to do i the Harvester - but the inverter configurations needs to have the minimal and large set of registers.

The Inverter interface could be changed to full_harvest and mini_harvest

**Comment by davmoz** [comment]
Proposal: 

1. Full read - All registers
2. Minimal read - essential registers (could be minimal read or full read depending on performance, and is the data sent to backend) 
3. Filter - Necessary registers

**Comment by h0bb3** [comment]
I think this is done Why no assignee and no status set?! @davmoz
