### ISSUE TITLE
Connecting to local IP - shows strange info?

### ISSUE THREAD

**Issue by frahlg** [srcfl/srcful-gateway#160]
When connecting to the GW over local IP in the webbrowser. It shows a totaly different IP and inverter type than I have configured earlier? 

![Screenshot 2024-04-01 at 18 27 08](https://github.com/srcfl/srcful-gateway/assets/6883838/15be0f59-189d-41ba-a5f3-fd37c057e552)

**Comment by h0bb3** [comment]
Lets just remove this form.
