### ISSUE TITLE
Monitor cryptochip revive 

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#175]
We need to understand if revive works and how many time it takes to actually fix the zeros pubkey issue. 

**End goal:** To proactivley run revive to avoid problems.

**Comment by davmoz** [comment]
Scenario:
* {"exception": "Failed to get public key cryptauthlib error code: 250", "endpoint": "/api/crypto"}
* configurator kraschar pga pubkey parsing (undefined, så crypto döden) 
* Revive 2 gånger - http://192.168.50.246/api/crypto/revive 
* http://192.168.50.246/api/crypto/revive
* Working

**Comment by h0bb3** [comment]
Several eGWs went offline this night. All are revved:
9694f57: x2
64982ae: x1
5e43744: x1

**Comment by h0bb3** [comment]
Offline due to crypto:
c3712ed: x1

**Comment by h0bb3** [comment]
interesting case that took two attempts. The first attempt returned:

64982ae

```
"status": "atcab_get_pubkey: 250 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000\nfinal return value (0 == success): 250\n"}
```

so actually another error code than the usual

**Comment by h0bb3** [comment]
64982ae

revived again on first attempt

**Comment by h0bb3** [comment]
c3712ed

revived on first attempt

**Comment by h0bb3** [comment]
64982ae

revived on first attempt

**Comment by h0bb3** [comment]
9694f57

revived on second attempt

**Comment by h0bb3** [comment]
Manual revive works so I think we close this one.

we had 10 revives done during these 4 weeks. Now we need to evaluate the automatic revive.
