### ISSUE TITLE
Test nmap

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#176]
test the implemented nmap endpoint. 

End goal: implement this in the app.

**Comment by davmoz** [comment]
seems to be working

**Comment by h0bb3** [comment]
Tested on a site that had lost connection to inverter. After scanning the new ip was shown and I could connect to the inverter using this ip address instead.

**Comment by h0bb3** [comment]
Another site that had lost connection to inverter due to change ip. After scanning the new ip was shown and I could connect to the inverter using this ip address instead.

**Comment by davmoz** [comment]
This is now available from: 

Gateway: 7439f32bd968d5d100e1e35febe989150aeee9a4 
App: [f00cc588fb2a598441c898ca7fb6ea5813c263c0](https://github.com/srcfl/srcful-configurator/commit/f00cc588fb2a598441c898ca7fb6ea5813c263c0)
