### ISSUE TITLE
Prepare for battery DER

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#177]
We need to start preparing for reading battery data. E.g. state of charge and maybe some status?

This would then need to be added to both the backend, explorer and app.

**Comment by davmoz** [comment]
This will be implemented once we start using sunspec.

**Comment by h0bb3** [comment]
Is there any issue for sunspec implementation?

**Comment by davmoz** [comment]
> Is there any issue for sunspec implementation?

Created one, https://github.com/srcfl/srcful-gateway/issues/216.

**Comment by davmoz** [comment]
Sunspec is in place, and we can now read e.g. SoC if present. 
Moving this to r10

**Comment by davmoz** [comment]
SoC and other battery-related fields should now be read when using SunSpec. closing
