### ISSUE TITLE
typo: pulikKey should be publicKey ?

### ISSUE THREAD

**Issue by erikarenhill** [srcfl/srcful-gateway#189]
https://github.com/srcfl/srcful-gateway/blob/ba9231658fbda359fdc36f9406df8abdc19d9c2f/server/web/handler/get/crypto.py#L20

**Comment by davmoz** [comment]
oops, fixed in https://github.com/srcfl/srcful-gateway/commit/26d9e7734d4fea3d0ae0fe20a4eacac58f1eef59.
