### ISSUE TITLE
read ac power in addition to dc power

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#193]
A deviation exists between current power readings from our energy API and local Modbus TCP readings. Address this and consider changing to AC power (or add it) as it is more interesting from the grid point of view.

**Comment by h0bb3** [comment]
I think both makes sense to collect as this information can be interesting for e.g. customers.

**Comment by h0bb3** [comment]
The main thing why we did not use AC was that the power was connected to (old) tokenomics and different inverters reported this using different models derrived from DC,  actual measurements,  or in some cases not at all (?)

**Comment by davmoz** [comment]
SunSpec readings now include AC and DC power. We create separate issues for each inverter model when using Modbus-only readings.
