### ISSUE TITLE
Refactor and replace hard-coded strings...

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#194]
Refactor and replace hard-coded strings with constants. Also create objects that describes common structures instead of using dictionaries. 

https://github.com/srcfl/srcful-gateway/blob/main/server/web/handler/get/network.py#L89

**Comment by h0bb3** [comment]
this sounds like two issues :)

I made an example of using properties instead of hard coded strings for the address handler. I think this works out pretty well and avoids some problems as a property is immutable... having no real immutable constants in python...

**Comment by h0bb3** [comment]
I at least got rid of the constanst and added props instead. If there is more to do we make a new issue.
