### ISSUE TITLE
Wrong IP-Address printed in ModbusTCP:Creating after a rescan

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#201]
Investigate this. 

Previously connected to 192.168.50.158, then disconnects, then finds 192.168.50.158, then print `ModbusTCP:Creating with: ('192.168.50.96', 1502..)` then actually connects to 192.168.50.158

```log
srcful-gw  | DEBUG:server.wifi.wifi:device ip address 192.168.50.48
srcful-gw  | INFO:server.web.handler.get.network:Scanning subnet 192.168.50.0/24 for modbus devices on ports [1502] with timeout 0.01.
srcful-gw  | INFO:server.inverters.ModbusTCP:Creating with: ('192.168.50.158', 1502, 'SOLAREDGE', 1)
srcful-gw  | INFO:server.tasks.openInverterPerpetualTask:Found inverter at 192.168.50.158, retry in 5 seconds...
srcful-gw  | INFO:server.bootstrap:Removing inverter from bootstrap: ('TCP', '192.168.50.96', 1502, 'SOLAREDGE', 1) not yet supported
srcful-gw  | INFO:server.bootstrap:Reading bootstrap file: /data/srcful/bootstrap.txt
srcful-gw  | INFO:server.inverters.ModbusTCP:Creating with: ('192.168.50.96', 1502, 'SOLAREDGE', 1)
srcful-gw  | INFO:server.bootstrap:Writing (w) inverter to bootstrap file: ('TCP', '192.168.50.158', 1502, 'SOLAREDGE', 1)
```

**Comment by h0bb3** [comment]
There is a fair chance that the inverter is also created in the process of the boostrap file thing (i.e just for the file handling stuff) 

ie this line in the log

`srcful-gw  | INFO:server.inverters.ModbusTCP:Creating with: ('192.168.50.96', 1502, 'SOLAREDGE', 1)`

is from reading the boostrap file and creating all existing tasks - so an inverter is created with the old ip as that is what was in the file before,.

This does not mean that there is any connection to the inverter nor any tasks added to the queue.

I.e I think there is no issue here @davmoz
