### ISSUE TITLE
feature request: add support for SMA Sunny Tripower

### ISSUE THREAD

**Issue by erikarenhill** [srcfl/srcful-gateway#212]
Sunny Tripower, at least the model STP 50-40 use other modbus registers than your current SMA implementation.

Here is a link for the docs / register mappings: https://files.sma.de/downloads/MODBUS-HTML_STP50-US-40_V11.zip

See the "modbuslist_en.html" in the zip-file.

The inverter has multiple DC inputs which reads from different registers
The total AC output can however be read from a single register

**Comment by davmoz** [comment]
Thanks! We will most likely use Sunspec for SMA.
