### ISSUE TITLE
Restore backward compatibility for creating various inverter types

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#225]
Reimplement functionality removed in issue #209 to support creation of different inverter types while maintaining backward compatibility.

**Comment by davmoz** [comment]
fixed in 0fd63921b9aa975fd11027722cdebd9d9c0621e0

**Comment by davmoz** [comment]
Also make them use the new object factory

**Comment by h0bb3** [comment]
done?

**Comment by davmoz** [comment]
fixed
