### ISSUE TITLE
Move ModbusScanHandler from the web endpoint

### ISSUE THREAD

**Issue by h0bb3** [srcfl/srcful-gateway#240]
We seem to need generic scannig of the network? so this should not be in the web endpoint. In general It would be better to make it a task. Then let the endpoint have a POST for scanning and a GET for the actual result. This is how the wifi scanning works so it would be better to mimic that pattern

E.g.

POST scan/502 - scan port 502
GET scan/502 get the result from the scan (could be empty)

**Comment by davmoz** [comment]
`ModbusScanHandler` is now moved to `server/web/handler/get/modbus_scan.py` and still takes query parameters:

```
http://{{host}}/inverter/modbus/scan?ports=502&timeout=0.1
``` 

Also added a startup task that does an initial scanning for the default ports (502, 1502, 8899, and 6607), available in a110da543f97cad271083a32e4232a4a21d13f2d. 

Both the startup task and the GET endpoint will cache the request result.
