### ISSUE TITLE
New Feature: Automatic Network Scanning for Inverters

### ISSUE THREAD

**Issue by frahlg** [srcfl/srcful-gateway#25]
Currently, our system requires manual IP input for inverter onboarding. This is not only time-consuming but can also be confusing for users who are not tech-savvy.

In order to improve the user experience during onboarding and make the setup process smoother, it would be beneficial to implement a new feature that automatically scans the local network for inverters.

This approach is already adopted by several services like Home Assistant, which successfully recognizes numerous devices in the local network without the need for manual IP input. This kind of automatic recognition will enhance our onboarding process by presenting the inverter in the app without any extra steps from the user side.

We believe that the development of this feature is relatively straightforward and it will significantly improve the overall user experience.

**Comment by davmoz** [comment]
nmap and get all with port 502 and 1502 open.

**Comment by frahlg** [comment]
I have no idea on where to begin to integrate this into the larger project. So .-... I'll just leave this ..

**Comment by h0bb3** [comment]
The code in  `get_ip_and_subnet()` will not work as expected when running in a Docker container - it is not possible to get the host machine ip and thus subnet from within a container.

Rather this needs to be injected as a parameter from the outside (i.e. via an env).

**Comment by davmoz** [comment]
Implemented this in https://github.com/srcfl/srcful-gateway/commit/323c4a77a4e619b1cc6ad32c9ac4c90e07258f0c. Seems to work at first glance, but need some testing.. 

Endpoint: `/api/inverter/modbus/scan`

<img width="1096" alt="image" src="https://github.com/srcfl/srcful-gateway/assets/26165830/208ea053-5af7-433d-a946-855460007b32">
