### ISSUE TITLE
Device Mac-address sometimes set to null 

### ISSUE THREAD

**Issue by davmoz** [srcfl/srcful-gateway#255]
Device objects can be created with a null MAC address when they are instantiated without an established socket connection. This occurs because the MAC address is typically obtained during the initial socket connection, but if a device object is created before this connection is made, the MAC address field remains unset in the ARP table. 

Move this to to `connect`

**Comment by h0bb3** [comment]
This was implemended in `_connect` for the modubus subclasses. Fixed during testing of #253
